import { formatDistanceToNow } from "date-fns";

var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

const msgList = [
  "Hey, how's it going?",
  "Did you watch the latest episode?",
  "What's for dinner tonight?",
  "I'm so tired today.",
  "Have you seen the news?",
  "How was your weekend?",
  "Can you believe it's already March?",
  "Did you hear about the new movie?",
  "What's your plan for the holidays?",
  "I need coffee ASAP.",
  "Just finished a great book!",
  "Let's catch up soon.",
  "How's work going?",
  "I'm craving pizza right now.",
  "Have you tried that new restaurant?",
  "It's freezing outside.",
  "Long time no see!",
  "Any exciting plans for the week?",
  "What's your favorite TV show?",
  "I'm stuck in traffic.",
  "What's your favorite song at the moment?",
  "Just finished my workout.",
  "Can't wait for the weekend!",
  "I'm feeling so productive today.",
  "How's your day going so far?",
  "Have you been to that new exhibit?",
  "I miss traveling so much.",
  "Let's go for a hike soon.",
  "What's the weather like there?",
  "I need a vacation.",
  "How's your family doing?",
  "Have you started any new hobbies?",
  "Let's plan a game night.",
  "I'm so hungry right now.",
  "Any good recommendations for movies?",
  "Just finished watching a series.",
  "I love this time of year.",
  "Let's grab lunch sometime.",
  "What's your favorite book genre?",
  "I'm feeling so motivated today.",
  "Did you hear about the new restaurant opening?",
  "Can't wait for summer!",
  "How's your pet doing?",
  "Let's go on a road trip!",
  "I'm so ready for spring.",
  "Have you tried cooking that recipe?",
  "Let's go shopping together.",
  "I'm planning a DIY project.",
  "Any plans for the holidays?",
  "Let's plan a movie night.",
];

export function generateRandomMsg() {
  return msgList[Math.floor(Math.random() * msgList.length)];
}

export const formatDate = (dateString) => {
  return formatDistanceToNow(new Date(dateString), { addSuffix: true });
};
